GET http://localhost:3000/tracks

###
GET http://localhost:3000/tracks/2

###
GET http://localhost:3000/users

###
GET http://localhost:3000/storage


###
POST http://localhost:3000/tracks
Content-Type: application/json

{
  "artist": {
    "name": "The Weeknd",
    "nickname": "Abel",
    "edad": 34
  },
  "album": {
    "name": "After Hours",
    "cover": "https://example.com/cover.jpg"
  }
}
